language: python
python:
  - "3.6" 
  - "3.7"
  - "3.8"
    #- "nightly"  # nightly build turned off for now because numpy cannot be installed using pip yet
install:
  - pip install -r requirements.txt
script:
  - python -m pytest pyopls/tests/
deploy:
  provider: pypi
  user: __token__
  password:
    secure: HJJK7VFqtvpfrGKm2Tvikmur5xVbeLIKT1d6sz+NR9KII9OYReTGi6gGjFSxmPOLTLKuMHpJ8GLfUipK0RiwQYZMe6ve9kuAX4w3Gcn3juR2CLRjc78zwg3u7vQzunuUmXO1vjDhIOawgnbwcaHKZ0bnnHCs39uwUfdxq673SrmlSLCNrRLLsfUOMycCX1HVtAlSDGvdPdsl6DMx+YqJp05uc6oVk50RgojQxjetJtonUcEeEIWXm6V/twQc4wa8mlt/ZnCnkF3kccQUp+a4/P7uoHzF6GLOjJ15rvPz6f/J8wZr1n9Jz5Ng0U4aJFX3clVMGJLcOaRf3owcydIQvfyKzwKuqPN0nnvPv4FMKTNPEMpLVwIc4PUJFrZ1g4013tZZT6zuEqKYrOPpz/nifobWhLUc2ktHt3t0B6VR2VOcYJRWlMpuI9gwAYq0dMtlnIWReYeerLWMLnpzFwAHfogOjKoCAIEPM/PmtjNh2hrYIZZhiH+wCuqcYG4SrC9J0azx8vXWzbxYPRNfvZpxmNjZ2kAeEYsQ0BEL1UI9839rmkOGyVqbEZ9VP1GHg5KsifmeD+VzZEaJOS+PYu8YPuHrfah7MYswaQC4uyU/vzEJlc3oZ/15rqzsgj9GKqWmMS25OvXxOilt9W5CpIKrV7nNzfn22JOKHRMwjPS28f8=
  skip_existing: true
